config/routes.rb
YourOpinion::Application.routes.draw do
  devise_for :companies, :controllers => { :registrations => "registrations" }
  get "home/index"
  get "home/survey"
  get "home/question"
  get "statistics/morris"
  get "statistics/donut"

  resources :surveys do
    resources :questions
    resources :customers do
      member do
        get 'more_feedback'
      end
    end
  end

  resources :customers do
    resources :answers
  end


  root to: "home#index"
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers

  TYPE_ANSWERS = ['Scale', 'Yes Or Not', 'Happy Level']

  validates :type_answer,
    :inclusion  => { :in => TYPE_ANSWERS,
    :message    => "%{value} is not a valid type answer" }

  validates :description, presence: true


  def case_answer(happy_level, yes_or_not, scale)
    result = case type_answer
    when 'Happy Level'
      happy_level.call
    when 'Yes Or Not'
      yes_or_not.call
    when 'Scale'
      scale.call
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
  before_filter :authenticate_company!
  before_action :protect_question_ownership!

  belongs_to :survey


  def create
    create! { collection_url }
  end

  def update
    update! { collection_url }
  end

  def resource_params
    params.require(:question).permit(:description, :type_answer, :survey_id)
  end

  # def collection
  #   get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(:page => params[:page], :per_page => per_page))
  # end

  def per_page
    6
  end

protected
  def protect_question_ownership!
    redirect_to(root_path) unless parent.company == current_company
  end
end

app/views/questions/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= action_name.humanize %> Survey</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= current_company.name %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <%= form_for([parent, resource], html: {role: "form" }) do |f| %>
                            <%= devise_error_messages! %>
                            <div class="form-group">
                                <%= f.label :description %>
                                <%= f.text_field :description, autocomplete: "true", class: "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= f.label :type_answer_scale, 'Scale', class: "radio-inline" %>
                                <%= f.radio_button :type_answer, 'Scale' %>

                                <%= f.label :type_answer_yes_or_not, 'Yes Or Not', class: "radio-inline" %>
                                <%= f.radio_button :type_answer, 'Yes Or Not' %>

                                <%= f.label :type_answer_happy_level, 'Happy Level', class: "radio-inline" %>
                                <%= f.radio_button :type_answer, 'Happy Level' %>

                            </div>

                            <%= f.submit "Save", class: "btn btn-default" %>
                            <button type="reset" class="btn btn-default">Reset Button</button>
                        <% end %>

                        <%= link_to "Back", :back %>
                    </div>
                    <!-- /.col-lg-6 (nested) -->


                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<%= link_to "Back", :back %>
<%= link_to 'New Question', new_survey_question_path(parent) %>
<%= link_to 'Take Survey', new_survey_customer_path(parent) %>
<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Type Answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |question| %>
      <tr>
        <td><%= question.description %></td>
        <td><%= question.type_answer %></td>
        <td>
          <%= link_to edit_survey_question_path(parent, question), class: "btn btn-xs btn-success" do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
          <% end -%>
        </td>
        <td>
          <%= link_to survey_question_path(parent, question), class: "btn btn-xs btn-warning" do %>
            <i class="fa fa-bar-chart-o fa-fw"></i> Statistic
          <% end -%>
        </td>
        <td>
          <%= link_to survey_question_path(parent, question), method: :delete, class: "btn btn-xs btn-danger" do %>
            <span class="glyphicon glyphicon-remove"></span> Destroy
          <% end -%>
        </td>
      </tr>
    <% end -%>
  </tbody>
</table>

<%#= will_paginate collection, renderer: BootstrapPagination::Rails %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "morris/morris-0.4.3.min", media: "all", "data-turbolinks-track" => true %>
<% end %>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Statistics</h1>
        <h4><%= resource.description %></h4>
        <h5><em><b>Total Answers:</b></em> <%= resource.answers.count %></h5>
        <h5>
            <% case resource.type_answer
                when 'Happy Level'%>
                <em><b>Total Satisfied:</b></em> <%= resource.answers.satisfied.count %>
                <em><b>Total Neutral:</b></em> <%= resource.answers.neutral.count %>
                <em><b>Total Unsatisfied:</b></em> <%= resource.answers.unsatisfied.count %>
            <%  when 'Yes Or Not'%>
                <em><b>Total Yeses:</b></em> <%= resource.answers.yes.count %>
                <em><b>Total Not:</b></em>   <%= resource.answers.not.count %>
            <%  when 'Scale'%>
                <em><b>Total:</b></em> <%= resource.answers.total_scale %>
            <% end -%>
        </h5>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Area Chart
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Bar Chart
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-bar-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Line Chart
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-line-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Donut Chart
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Morris.js Usage
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p>Morris.js is a jQuery based charting plugin created by Olly Smith. In SB Admin, we are using the most recent version of Morris.js which includes the resize function, which makes the charts fully responsive. The documentation for Morris.js is available on their website, <a target="_blank" href="http://www.oesmith.co.uk/morris.js/">http://www.oesmith.co.uk/morris.js/</a>.</p>
                <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://www.oesmith.co.uk/morris.js/">View Morris.js Documentation</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>

<% content_for :javascript do %>
    <%= javascript_include_tag "statistics.js"%>
    <%= javascript_include_tag "plugins/morris/raphael-2.1.0.min"%>
    <%= javascript_include_tag "plugins/morris/morris"%>
    <%= javascript_include_tag "demo/morris-demo"%>
<% end %>
<!-- /.row -->