config/routes.rb
YourOpinion::Application.routes.draw do
  devise_for :companies, :controllers => { :registrations => "registrations" }
  get "home/index"
  get "home/survey"
  get "home/question"
  get "statistics/morris"
  get "statistics/donut"

  resources :surveys do
    resources :questions
    resources :customers do
      member do
        get 'more_feedback'
      end
    end
  end

  resources :customers do
    resources :answers
  end


  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @restaurant = Company.find_by(name: 'Restaurant')
    @airline = Company.find_by(name: 'Airline')

    render layout: 'landing'
  end
end

app/views/home/index.html.erb
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Your Opinion</h1>
                    <h3>Demo</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <%= link_to new_survey_customer_path(@restaurant.surveys.first), class: "btn btn-default btn-lg" do %>
                                <i class="glyphicon glyphicon-glass"></i> <span class="network-name">Take survey restaurant</span>
                            <% end -%>
                        </li>

                        <li>
                            <%= link_to new_survey_customer_path(@airline.surveys.first), class: "btn btn-default btn-lg" do %>
                                <i class="glyphicon glyphicon-plane"></i> <span class="network-name">Take survey Airline</span>
                            <% end -%>
                        </li>
                    </ul>
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <%= link_to new_company_session_path, class: "btn btn-default btn-lg" do %>
                                <i class="glyphicon glyphicon-user"></i> <span class="network-name">Login with a Company</span>
                            <% end -%>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Create online surveys with ease.<br />
Get great feedback.</h2>
                <p class="lead">Review your customer is important, do it possible with "Your Opinion" <%= link_to 'Visit their website', new_company_registration_path %> to become a member.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag "ipad.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-b">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Knowing the future</h2>
                <p class="lead">Notice the trend of your business with statistics</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <%= image_tag "doge.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Google Web Fonts and
                    <br>Font Awesome Icons</h2>
                <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag "phones.png", class: "img-responsive" %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="banner">

    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <h2>Connect to Start Bootstrap:</h2>
            </div>
            <div class="col-lg-6">
                <ul class="list-inline banner-social-buttons">
                    <li><a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li><a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.banner -->

app/views/home/survey.html.erb
<form class="form-horizontal">
    <fieldset>

    <!-- Form Name -->
    <legend>Survey</legend>

    <!-- Textarea -->
    <div class="control-group">
      <label class="control-label" for="survey_introductory_text">Introductory Text</label>
      <div class="controls">
        <textarea id="survey_introductory_text" name="survey_introductory_text">e.g. Welcome! The objective of this survey will be ...</textarea>
      </div>
    </div>

    <!-- Textarea -->
    <div class="control-group">
      <label class="control-label" for="survey_goodbye_message">Goodbye Message</label>
      <div class="controls">
        <textarea id="survey_goodbye_message" name="survey_goodbye_message">e.g. Thank you for answering this survey</textarea>
      </div>
    </div>

    <!-- Text input-->
    <div class="control-group">
      <label class="control-label" for="survey_customer">Name</label>
      <div class="controls">
        <input id="survey_customer" name="survey_customer" type="text" placeholder="e.g. Emanuel" class="input-xlarge">
        <p class="help-block">Enter your name here if you wish (this field is not required)</p>
      </div>
    </div>

    <!-- Select Basic -->
    <div class="control-group">
      <label class="control-label" for="survey_sex">Sex</label>
      <div class="controls">
        <select id="survey_sex" name="survey_sex" class="input-xlarge">
          <option>Female</option>
          <option>Male</option>
        </select>
      </div>
    </div>

    <!-- Text input-->
    <div class="control-group">
      <label class="control-label" for="survey_max_questions">Max Questions</label>
      <div class="controls">
        <input id="survey_max_questions" name="survey_max_questions" type="text" placeholder="e.g. 5" class="input-xlarge">
        <p class="help-block">Indicate whether the survey questions have a limit per user (this field is not required)</p>
      </div>
    </div>

    <!-- Textarea -->
    <div class="control-group">
      <label class="control-label" for="survey_comment">Comment</label>
      <div class="controls">
        <textarea id="survey_comment" name="survey_comment">Yur opinions are welcome here :)</textarea>
      </div>
    </div>

    <!-- Button -->
    <div class="control-group">
      <label class="control-label" for="singlebutton">Save</label>
      <div class="controls">
        <button id="singlebutton" name="singlebutton" class="btn btn-primary">Save</button>
      </div>
    </div>

    </fieldset>
</form>