config/routes.rb
YourOpinion::Application.routes.draw do
  devise_for :companies, :controllers => { :registrations => "registrations" }
  get "home/index"
  get "home/survey"
  get "home/question"
  get "statistics/morris"
  get "statistics/donut"

  resources :surveys do
    resources :questions
    resources :customers do
      member do
        get 'more_feedback'
      end
    end
  end

  resources :customers do
    resources :answers
  end


  root to: "home#index"
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :company

  has_many :questions
  has_many :customers
  has_many :answers, through: :questions
end

app/controllers/surveys_controller.rb
class SurveysController < InheritedResources::Base
  before_filter :authenticate_company!
  before_action :protect_survey_ownership!, only: [:edit]

  def index
    @surveys = current_company.surveys.paginate(:page => params[:page], :per_page => per_page)
  end

  def create
    @survey = Survey.new(resource_params)
    @survey.company_id = current_company.id
    create! { collection_url }
  end

  def update
    update! { collection_url }
  end



  def collection
    get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(:page => params[:page], :per_page => per_page))
  end

  def per_page
    6
  end

  protected

  def resource_params
    params.require(:survey).permit(:introductory_text, :goodbye_message, :max_questions, :main_question, :company_id)
  end

  def protect_survey_ownership!
    redirect_to(root_path) unless resource.company == current_company
  end
end

app/views/surveys/_form.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= action_name.humanize %> Survey</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <%= current_company.name %>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <%= form_for(resource, html: {role: "form" }) do |f| %>
                            <div class="form-group">
                                <%= f.label :introductory_text %>
                                <%= f.text_area :introductory_text, class: "form-control", rows: "3" %>
                            </div>

                            <div class="form-group">
                                <%= f.label :goodbye_message %>
                                <%= f.text_area :goodbye_message, class: "form-control", rows: "3" %>
                            </div>

                            <div class="form-group">
                                <%= f.label :max_questions %>
                                <%= f.text_field :max_questions, autocomplete: "true", class: "form-control" %>
                            </div>

                            <div class="form-group">
                                <%= f.label :main_question %>
                                <%= f.text_field :main_question, autocomplete: "true", class: "form-control" %>
                            </div>

                            <%= f.submit "Save", class: "btn btn-default" %>
                            <button type="reset" class="btn btn-default">Reset Button</button>
                        <% end %>

                        <%= link_to "Back", :back %>
                    </div>
                    <!-- /.col-lg-6 (nested) -->


                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/surveys/edit.html.erb
<%= render 'form' %>

app/views/surveys/index.html.erb
<%= link_to 'New Survey', new_survey_path %>
<table class="table">
  <thead>
    <tr>
      <th>Created at</th>
      <th>Introductory Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |survey| %>
      <tr>
        <td><%= survey.created_at %></td>
        <td><%= survey.introductory_text %></td>
        <td>
          <%= link_to edit_survey_path(survey), class: "btn btn-xs btn-success" do %>
            <span class="glyphicon glyphicon-edit"></span> Edit
          <% end -%>
        </td>
        <td>
          <%= link_to survey_questions_path(survey), class: "btn btn-xs btn-success" do %>
            <span class="glyphicon glyphicon-edit"></span> Questions
          <% end -%>
        </td>
        <td>
          <%= link_to survey_path(survey), method: :delete, class: "btn btn-xs btn-danger" do %>
            <span class="glyphicon glyphicon-remove"></span> Destroy
          <% end -%>
        </td>
      </tr>
    <% end -%>
  </tbody>
</table>

<%= will_paginate collection, renderer: BootstrapPagination::Rails %>

app/views/surveys/new.html.erb
<%= render 'form' %>